<td><%= ial_id %></td>
<td><%= name %></td>
<td><%= category %></td>
<td><%= area_km2 %></td>
<td><%= Math.round(pressure_score*100)/100 %></td>
<td><%= Math.round(habitat_score*100)/100 %></td>
<td><%= Math.round(response_score*100)/100 %></td>
<td><%= Math.round(biodiversity_score*100)/100 %></td>
<td><%= 'TO DO' %></td>
<td><%= species %></td>
<td><%= Math.round(taxon_site_overlap*100)/100 %></td>
<td><%= Math.round(uncertainty_score*100)/100 %></td>
