<td><%= ial_id %></td>
<td><%= name %></td>
<td><%= category %></td>
<td><%= area_km2 %></td>
<td><%= pressure_score %></td>
<td><%= habitat_score %></td>
<td><%= response_score %></td>
<td><%= biodiversity_score %></td>
<td><%= 'TO DO' %></td>
<td><%= species %></td>
<td><%= 'TO DO' %></td>
<td><%= uncertainty_score %></td>
